services:
  db:
    image: postgres:15-alpine
    restart: always
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=REPLACE_WITH_ENV_VALUE
      - DATABASE_URI=REPLACE_WITH_ENV_VALUE
     
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

